// Code generated by Slice Machine. DO NOT EDIT.

import Bio from './Bio/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';


export const components = {
	bio: Bio,
	hero: Hero,
	rich_text: RichText,

};
