// Code generated by Slice Machine. DO NOT EDIT.

import Bio from './Bio/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import RichText from './RichText/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	bio: Bio,
	experience: Experience,
	hero: Hero,
	image_block: ImageBlock,
	rich_text: RichText,
	tech_list: TechList
};
